version: '3'

services:

  app:
    image: filebrowser/filebrowser
    volumes:
      # Base scope of filebrowser access on your server MUST BE CHANGED
      - /var/data:/srv
      - /var/data/filebrowser/config.json:/etc/config.json:ro
      - /var/data/filebrowser/:/config/
    networks:
      - internal
      
  proxy:
    image: funkypenguin/oauth2_proxy:latest
    env_file: /var/data/config/filebrowser/filebrowser.env
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:filebrowser.funkypenguin.co.nz
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /var/data/config/filebrowser/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://app:80
      -redirect-url=https://filebrowser.funkypenguin.co.nz
      -http-address=http://0.0.0.0:4180
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt
      
networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.46.0/24
