version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: c_samba 
    environment: 
      - NMBD="true"
      - SMB=true      
      - GROUPID=1000
      - USERID=1000
      - TZ=${TZ}
      - PERMISSIONS=0775
      - WORKGROUP=${WORKGROUP}
      - USER="${USERNAME}";"${USERPASSWORD}"
      - SHARE=${SHARE}
      - SHARE2-${SHARE2}
    volumes: 
      - ${MOUNT}:/local
      - ${MOUNT2}:/local2
    tty: true
    network_mode: "bridge"
    ports: 
      - "137:137"
      - "138:138"
      - "139:139"
      - "445:445"
    restart: unless-stopped
