version: '3.4'

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
    volumes:
      - ${CONFIGDIR}:/config
      - ${TVDIR}:/tv
      - ${WATCHDIR}:/downloads
    tty: true
    network_mode: "bridge"
    ports:
      - ${PORT}:8989
    restart: unless-stopped