kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-app
  namespace: nextcloud
  annotations:
    backup.kubernetes.io/deltas: P1D P7D
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
