---
networks:
  c0_proxy:
    name: c0_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24
volumes:
  open-webui:

services:
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      - c0_proxy
    privileged: true # true for VM. false for unprivileged LXC container on Proxmox.
    ports:
      - 2375:2375 # Do not expose this to the internet with port forwarding
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, Portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer

  # tdarr:
  #   container_name: tdarr_node
  #   image: haveagitgat/tdarr_node
  #   network_mode: bridge
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - serverIP=192.168.1.210
  #     - webUIPort=8265
  #     - serverPort=8266
  #     - TZ=Europe/Dublin
  #     - inContainer=true
  #     - PUID=1000
  #     - PGID=1000
  #     - nodeName=castle0
  #   volumes:
  #     - /netmedia/library/movies:/home/Tdarr/Media/movies
  #     - /netmedia/library/tv:/home/Tdarr/Media/tv
  #     - ./data/downloads/cache/:/temp
  #     - ./data/tdarr/data/:/app/server
  #     - ./data/tdarr/data/:/app/configs
  #     - ./data/tdarr/data/:/app/logs
  #   ports:
  #     - 8265:8265
  #     - 8266:8266
  #   devices:
  #     - /dev/dri:/dev/dri
  #   logging:
  #     options:
  #       max-size: 10m
  #       max-file: 5
  #   restart: unless-stopped
  open-webui:
    networks:
      c0_proxy:
    ports:
      - 3000:8080
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - open-webui:/app/backend/data
    environment:
      - "OLLAMA_BASE_URL=http://192.168.1.17:11434"
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:cuda
    extra_hosts:
      - host.docker.internal:host-gateway

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/syncthing/config:/config
      - ${SYNC_DATA_DIR}:/data1
    ports:
      - ${SYNC_PORT_GUI:-8384}:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
