---
networks:
  c0_proxy:
    name: c0_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24
volumes:
  open-webui:
  ollama:
  postgres:

services:
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      - c0_proxy
    privileged: true # true for VM. false for unprivileged LXC container on Proxmox.
    ports:
      - 2375:2375 # Do not expose this to the internet with port forwarding
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, Portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer

  # tdarr:
  #   container_name: tdarr_node
  #   image: haveagitgat/tdarr_node
  #   network_mode: bridge
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - serverIP=192.168.1.210
  #     - webUIPort=8265
  #     - serverPort=8266
  #     - TZ=Europe/Dublin
  #     - inContainer=true
  #     - PUID=1000
  #     - PGID=1000
  #     - nodeName=castle0
  #   volumes:
  #     - /netmedia/library/movies:/home/Tdarr/Media/movies
  #     - /netmedia/library/tv:/home/Tdarr/Media/tv
  #     - ./data/downloads/cache/:/temp
  #     - ./data/tdarr/data/:/app/server
  #     - ./data/tdarr/data/:/app/configs
  #     - ./data/tdarr/data/:/app/logs
  #   ports:
  #     - 8265:8265
  #     - 8266:8266
  #   devices:
  #     - /dev/dri:/dev/dri
  #   logging:
  #     options:
  #       max-size: 10m
  #       max-file: 5
  #   restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - POSTGRES_USER=${N8N_POSTGRES_USER:-n8n}
      - POSTGRES_DB=${N8N_POSTGRES_DB:-n8n}
    restart: unless-stopped

  open-webui:
    networks:
      c0_proxy:
    ports:
      - ${OPENWEBUI_PORT:-8080}:8080
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu
    volumes:
      - open-webui:/app/backend/data
      - ${DATA_DIR}/open-webui/data:/data
      - ${DATA_DIR}/open-webui/models:/models
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
      - LOG_LEVEL=${OPENUI_LOG_LEVEL:-info}
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
      - LOG_LEVEL=debug
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    volumes:
      - ollama:/root/.ollama
      - ${DATA_DIR}/ollama/models:/models
    ports:
      - "11434:11434"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    networks:
      - c0_proxy
    restart: unless-stopped
