version: "3"

services:

  registry-mirror:
    image: registry
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:registry-mirror.funkypenguin.co.nz
        - traefik.port=5000
    ports:
      - 5000:5000
    volumes:
      - /var/data/registry/registry-mirror-data:/var/lib/registry
      - /var/data/config/registry/registry-mirror-config.yml:/etc/docker/registry/config.yml

networks:
  traefik_public:
    external: true
