version: "3.7"
########################### Networks
networks:
  marketplace:
    driver: bridge

########################### SERVICES
services:

  watchtower:
    image: containrrr/watchtower 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer-ce:
    ports:
        - '8000:8000'
        - '9000:9000'
    container_name: portainer
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - 'portainer_data:/data'
    image: portainer/portainer-ce

  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      # - CLI_ARGS= #optional
    volumes:
      - ${DATADIR}/duplicati/config:/config
      - ${DATADIR}/duplicati/backups:/backups
      - ${DATADIR}/duplicati/source:/source
      - /local:/localdata
    ports:
      - 8200:8200
    restart: unless-stopped

  wireguard:
    container_name: wireguard
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=${TZ}
        - SERVERURL=${WCDOMAIN}
        - SERVERPORT=${WCSERVERPORT}
        - PEERS=${PEERS}
        - PEERDNS=auto
        - INTERNAL_SUBNET=${WCINTERNALIP}
        - ALLOWEDIPS=${VCALLOWEDIPS}
    ports:
        - ${WCSERVERPORT}:51820/udp
    volumes:
        - ${DATADIR}/wireguard/config:/config
        - /lib/modules:/lib/modules
    restart: unless-stopped
    image: linuxserver/wireguard

########################### volumes
volumes:
  portainer_data: