version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true
########################### SERVICES
services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      marketplace:
        ipv4_address: 192.168.10.40


  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: unless-stopped
    networks:
      marketplace:
        ipv4_address: 192.168.10.41
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: 192.168.10.40
      MYSQL_HOSTNAME: 192.168.10.100
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole
      MYSQL_USER: server
      MYSQL_PASSWORD: homeland
