version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

########################### SERVICES
services:

  odoo_web:
    image: odoo:15.0
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /local/data/odoo/config:/etc/odoo
      - /local/data/odoo/addons:/mnt/extra-addons
    ports:
      - "8069:8069"
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      # - /local/data/odoo-db-data/pgdata:/var/lib/postgresql/data/pgdata
      - /local/data/odoo-db-data:/var/lib/postgresql/data/

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    volumes:
      - /local/data/dolibarr/mariadb:/local

  web:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_URL_ROOT: 'http://192.168.1.3'
      PHP_INI_DATE_TIMEZONE: 'Europe/Dublin'
    ports:
        - "80:80"
    links:
        - mariadb
    volumes:
      - /local/data/dolibarr/dolibarr:/local
      - /local/data/dolibarr-docs:/var/www/documents

volumes:
  odoo-web-data: