version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

########################### SERVICES
services:

  # odoo_web:
  #   image: odoo:15.0
  #   depends_on:
  #     - db
  #   volumes:
  #     - odoo-web-data:/var/lib/odoo
  #     - /local/data/odoo/config:/etc/odoo
  #     - /local/data/odoo/addons:/mnt/extra-addons
  #   ports:
  #     - "8069:8069"
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_PASSWORD=odoo
  #     - POSTGRES_USER=odoo
  #   volumes:
  #     # - /local/data/odoo-db-data/pgdata:/var/lib/postgresql/data/pgdata
  #     - /local/data/odoo-db-data:/var/lib/postgresql/data/

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: DuAnxLJ4NEN4Gd
      MYSQL_DATABASE: dolibarr
    volumes:
      - /local/data/dolibarr/mariadb:/local

  dolibarr:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: DuAnxLJ4NEN4Gd
      DOLI_DB_NAME: dolibarr
      DOLI_ADMIN_PASSWORD: GjoGKAN6e2qcT8
      DOLI_URL_ROOT: 'http://192.168.1.3'
      PHP_INI_DATE_TIMEZONE: 'Europe/Dublin'
    ports:
        - "8080:80"
    links:
        - mariadb
    volumes:
      - /local/data/dolibarr/dolibarr:/local
      - /local/data/dolibarr-docs:/var/www/documents

  nginxpm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'
    volumes:
      - local/data/nginxpm/data:/data
      - local/data/nginxpm/letsencrypt:/etc/letsencrypt

  wp_db:
    container_name:  wp_database
    image: mariadb 
    ports: 
      - "3306:3306"
    volumes:
      - /local/data/wordpress/wp_db/dep/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: T7Jbc9yymJkk3P
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: eS59ihkyewHsH2

  wordpress:
    image: wordpress
    container_name: wordpress 
    depends_on:
      - wp_db
    ports:
      - "8080:80"
      - "8443:443"
    volumes: 
      - /local/data/wordpress/theme:/var/www/html/wp-content/themes/theme_name
      - /local/data/wordpress/dep/plugins:/var/www/html/wp-content/plugins
      - /local/data/wordpress/dep/uploads:/var/www/html/wp-content/uploads
    links: 
      - wp_db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: eS59ihkyewHsH2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - wp_db
    restart: always
    ports:
      - "8081:80"
    environment:
     - PMA_ARBITRARY=1

################ Volumes

# volumes:
  # odoo-web-data:
