version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

########################### SERVICES
services:

  dolibarr:
    container_name: dolibarr
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: ${DOLI_DB_PASS}
      DOLI_DB_NAME: dolibarr
      DOLI_ADMIN_PASSWORD: ${DOLI_ADMIN_PASS}
      DOLI_URL_ROOT: ${DOLI_URL_ROOT}
      PHP_INI_DATE_TIMEZONE: ${TZ}
    ports:
        - "8081:80"
    links:
        - mariadb
    volumes:
      - /local/data/dolibarr/dolibarr:/local
      - /local/data/dolibarr-docs:/var/www/documents
      - /local/data/dolibar/www:/var/www/html/custom

  wp_db:
    container_name:  wp_database
    image: mariadb 
    ports: 
      - "3306:3306"
    volumes:
      - /local/data/wordpress/wp_db/dep/mysql:/docker-entrypoint-initdb.d
      - /local/data/wordpress/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: T7Jbc9yymJkk3P
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: eS59ihkyewHsH2

  wordpress:
    image: wordpress
    container_name: wordpress 
    depends_on:
      - wp_db
    ports:
      - "10080:80"
      - "10443:443"
    volumes: 
      - /local/data/wordpress/theme:/var/www/html/wp-content/themes/theme_name
      - /local/data/wordpress/dep/plugins:/var/www/html/wp-content/plugins
      - /local/data/wordpress/dep/uploads:/var/www/html/wp-content/uploads
      - /local/data/wordpress/var/www:/var/www/html
    links: 
      - wp_db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: eS59ihkyewHsH2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - wp_db
    restart: always
    ports:
      - "8081:80"
    environment:
     - PMA_ARBITRARY=1



  antennas:
      container_name: antennas
      environment:
          - 'ANTENNAS_URL=http://192.168.1.11:5004'
          - 'TVHEADEND_URL=http://server:homeland@192.168.1.13:9981'
          - TUNER_COUNT=1
      ports:
          - '5004:5004'
      image: thejf/antennas

################ Volumes

# volumes:
  # odoo-web-data:
