version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

########################### SERVICES
services:

  odoo_web:
    image: odoo:15.0
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /local/data/odoo/config:/etc/odoo
      - /local/data/odoo/addons:/mnt/extra-addons
    ports:
      - "8069:8069"
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      # - /local/data/odoo-db-data/pgdata:/var/lib/postgresql/data/pgdata
      - /local/data/odoo-db-data:/var/lib/postgresql/data/

volumes:
  odoo-web-data: