version: '2.2'
########################### Networks
networks:
  marketplace:
    external: true

########################### SERVICES
services:
  sharelatex:
    image: sharelatex/sharelatex:with-texlive-full
    container_name: latex_sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - mongo
      - redis
    environment:
      SHARELATEX_APP_NAME: Overleaf Environment
      SHARELATEX_MONGO_URL: mongodb://192.168.10.31/sharelatex
      # Same property, unfortunately with different names in
      # different locations
      SHARELATEX_REDIS_HOST: 192.168.10.32
      REDIS_HOST: 192.168.10.32
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var
    volumes:
      - /local/data/sharelatex_data:/var/lib/sharelatex
    networks:
      marketplace:
        ipv4_address: 192.168.10.30
    ports:
      - 8088:80
    restart: always      

  mongo:
      restart: always
      image: mongo:4.0
      container_name: latex_mongo
      expose:
          - 27017
      volumes:
          - /local/data/mongo_data:/data/db
      healthcheck:
          test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
          interval: 10s
          timeout: 10s
          retries: 5
      networks:
        marketplace:
          ipv4_address: 192.168.10.31

  redis:
      restart: always
      image: redis:5
      container_name: latex_redis
      expose:
          - 6379
      volumes:
          - /local/data/redis_data:/data
      networks:
        marketplace:
          ipv4_address: 192.168.10.32
