version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: "192.168.1.0/24"

########################### SERVICES
services:

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    networks:
      dockervlan:
        ipv4_address: ${ADAWARE_IP}
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${LOCALDATADIR}/adguard/workdir:/opt/adguardhome/work
      - ${LOCALDATADIR}/adguard/confdir:/opt/adguardhome/conf
    restart: unless-stopped

  nginxpm:
    container_name: service_proxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - nginxpm_data:/data
      - ${LOCALDATADIR}/nginxpm/letsencrypt:/etc/letsencrypt
    networks:
      marketplace:
        ipv4_address: 192.168.10.21
    ports:
      - '80:80'
      - '443:443'
      - '81:81'

  # nginx-rtmp:
  #   ports:
  #       - '1935:1935'
  #   container_name: nginx-rtmp
  #   image: tiangolo/nginx-rtmp
  #   networks:
  #     marketplace:
  #       ipv4_address: 192.168.10.29

########################### volumes
volumes:
  nginxpm_data:
  portainer_data:
  pihole_etc-pihole:
  pihole_etc-dnsmasq.d:

