version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          # ip_range: "192.168.1.252/31"
          # gateway: "192.168.1.1"

########################### SERVICES
services:

  pihole:
    container_name: pcd0_pihole
    image: pihole/pihole:latest
    networks:
      dockervlan:
        ipv4_address: 192.168.1.254
      marketplace:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLEGUIPASSWORD}
      PIHOLE_DNS_: 1.1.1.1;8.8.8.8
      WEBTHEME: "default-auto"
    volumes:
      - 'pihole_etc-pihole:/etc/pihole'
      - 'pihole_etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  nginxpm:
    container_name: pcd0_proxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      marketplace:
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'
    volumes:
      - nginxpm_data:/data
      - /local/data/nginxpm/letsencrypt:/etc/letsencrypt

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - MYSQL_ROOT_PASSWORD=${mariadbpassword}
      - TZ=${TZ}
      - MYSQL_USER=server
    volumes:
      - /local/data/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - /local/data/workbench/config:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

########################### volumes
volumes:
  nginxpm_data:
  portainer_data:
  pihole_etc-pihole:
  pihole_etc-dnsmasq.d:

