version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          # ip_range: "192.168.1.252/31"
          # gateway: "192.168.1.1"

########################### SERVICES
services:

  pihole:
    container_name: service_pihole
    image: pihole/pihole:latest
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLEGUIPASSWORD}
      PIHOLE_DNS_: 1.1.1.1;8.8.8.8
      WEBTHEME: "default-auto"
    volumes:
      - 'pihole_etc-pihole:/etc/pihole'
      - 'pihole_etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      dockervlan:
        ipv4_address: 192.168.1.254
      marketplace:
        ipv4_address: 192.168.10.20
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    cap_add:
      - NET_ADMIN
    tty: true
    restart: unless-stopped

  nginxpm:
    container_name: service_proxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - nginxpm_data:/data
      - /local/data/nginxpm/letsencrypt:/etc/letsencrypt
    networks:
      marketplace:
        ipv4_address: 192.168.10.21
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: service_mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - MYSQL_ROOT_PASSWORD=${mariadbpassword}
      - TZ=${TZ}
      - MYSQL_USER=server
    volumes:
      - /local/data/mariadb/config:/config
    networks:
      marketplace:
        ipv4_address: 192.168.10.100
    ports:
      - 3306:3306        
    restart: unless-stopped

  nginx-rtmp:
    ports:
        - '1935:1935'
    container_name: nginx-rtmp
    image: tiangolo/nginx-rtmp
    networks:
      marketplace:
        ipv4_address: 192.168.10.29

########################### volumes
volumes:
  nginxpm_data:
  portainer_data:
  pihole_etc-pihole:
  pihole_etc-dnsmasq.d:

