version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

########################### VOLUMES
volumes:
    dolibarr_db:

########################### SERVICES
services: 

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    networks:
      marketplace:
    volumes:
      - dolibarr_db:/var/lib/mysql

  web:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_URL_ROOT: 'http://tickets.capparelli.ie'
      PHP_INI_DATE_TIMEZONE: 'Europe/Dublin'
    ports:
      - "8080:80"
    networks:
      marketplace:
    links:
      - mariadb
    volumes:
      - /local/dolibarr/documents:/var/www/documents
      - /local/dolibarr/custom:/var/www/html/custom