version: "3.7"
########################### Networks
# networks:

########################### VOLUMES
# volumes:

########################### SERVICES
services: 

  request-tracker:
    container_name: request_tracker
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - RT_WEB_PORT=8080
    image: 'netsandbox/request-tracker:5.0'