version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true

########################### VOLUMES
volumes:
    leantime_db_data: {}

########################### SERVICES
services: 

  leantime_db:
    image: mysql:5.7
    networks:
      marketplace:     
    container_name: leantime_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'B^fd43H63FXvs'
      MYSQL_DATABASE: 'leantime'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'BK4%6dsh6SFfgg'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

  leantime_web:
    image: leantime/leantime:latest
    container_name: leantime
    environment:
      LEAN_DB_HOST: 'leantime_db'
      LEAN_DB_USER: 'admin'
      LEAN_DB_PASSWORD: 'BK4%6dsh6SFfgg'
      LEAN_DB_DATABASE: 'leantime'
    ports:
      - "8080:80"
    depends_on:
      - leantime_db
