services:
  auth:
    container_name: auth    
    image: authelia/authelia:latest
    ports:
      - 9091:9091
    volumes:
      - /mnt/user/appdata/authelia:/config
    restart: unless-stopped
    depends_on:
      - auth-redis
      - auth-mariadb

  auth-redis:
    container_name: auth-redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    volumes:
      - /mnt/user/appdata/auth-redis:/bitnami/
    environment:
      REDIS_PASSWORD: ${AUTH_REDIS_PASS}
    restart: unless-stopped

  auth-mariadb:
    container_name: auth-mariadb
    image: linuxserver/mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - /mnt/user/appdata/auth-mariadb:/config
    environment:
      MYSQL_ROOT_PASSWORD: ${MSQL_ROOT_PW}
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: authelia
      MYSQL_USER: authelia
      MYSQL_PASSWORD: ${MSQL_PW}  
    restart: unless-stopped
      