version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true
  # warehouse:
  #   external: true
  socket_proxy:
    external: true

########################### SERVICES
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    networks: 
      marketplace:
        ipv4_address: 192.168.90.72
    ports:
      - "25565:25565"
    volumes:
      - /mineos:/data
    environment:
      - EULA=TRUE
      - VERSION=LATEST
      - TYPE=FORGE
      - DIFFICULTY=NORMAL
      - MAX_PLAYERS=10
      - ALLOW_NETHER=true
      - ENABLE_COMMAND_BLOCK=true
      - SEED="-43121277"
      - ALLOW_FLIGHT=true
      - ENABLE_AUTOPAUSE=false
    restart: always

