version: "3.7"
########################### Networks
networks:
  marketplace:
    external: true
  warehouse:
    external: true
  # local0:
  #   driver: bridge    
  #   ipam:
  #     config:
  #       - subnet: 192.168.0.0/24
  rollcall:
    driver: macvlan
    driver_opts: 
      parent: enp1s0
    ipam:
      config: 
        - subnet: 192.168.1.0/24
########################### SERVICES
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks: 
      rollcall:
        ipv4_address: ${PIHOLEIPADDR}
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLEGUIPASSWORD}
      DNS1: 127.0.0.1
      DNS2: 1.0.0.1
    volumes:
      - ${CONFIGDIR}/pihole/pihole_etc:/etc/pihole
      - ${CONFIGDIR}/pihole/pihole_dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    restart: unless-stopped

  delugevpn:
    image: binhex/arch-delugevpn
    container_name: delugevpn
    environment: 
      - TZ=${TZ}
      - VPN_ENABLED=yes
      - VPN_USER=${VPNUSER}
      - VPN_PASS=${VPNPASSWORD}
      - VPN_PROV=${VPNPROVIDER}
      - STRICT_PORT_FORWARD=no 
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=${SETNETWORK}
      - NAME_SERVERS=${DNSSERVERS}
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - ADDITIONAL_PORTS=1234
      - DEBUG=false
      - UMASK=${UMASK}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes: 
      - ${CONFIGDIR}/deluge/config:/config
      - ${CONFIGDIR}/deluge/data:/data
      - ${TEMPDIR}:/tmp 
      - ${DOWNLOADDIR}:/downloads
      - ${WATCHDIR}:/watch 
    tty: true
    networks:
      - marketplace
    cap_add: 
      - NET_ADMIN
    ports: 
      - 58846:58846
      - 58946:58946
      - ${DELUGEPORT}:8112
      - ${PRIVOXYPORT}:8118
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment: 
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    volumes: 
      - ${CONFIGDIR}/jackett:/config
      - ${WATCHDIR}:/watch
    tty: true
    networks:
      - marketplace
    ports: 
      - 6003:9117
    restart: unless-stopped

  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 80:80
      - 443:443 #optional
    restart: unless-stopped

  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - <path to data>:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=<yourdbpass>
      - DB_DATABASE=bookstackapp
    volumes:
      - /path/to/data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=<yourdbpass>
    volumes:
      - /path/to/data:/config
    restart: unless-stopped