services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${APPDIR}/plex/config:/config
      - ${MEDIADIR}/tvshows:/tv
      - ${MEDIADIR}/movies:/movies
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APPDIR}/tautulli:/config
    networks:
      - plex-proxy
    ports:
      - 8181:8181
    restart: unless-stopped

networks:
  plex-proxy:
    driver: bridge