services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - URL=${DOMAINNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - PROPAGATION=120
      - EMAIL=${DNSEMAIL}
      - ONLY_SUBDOMAINS=false
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-auto-reload|linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy #delete if not wanted or necessary
    volumes:
      - ${APPDIR}/swag:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 18443:443
      - 1880:80
    restart: unless-stopped
    networks:
      br0:

networks:
  br0:
    external: true
    