apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secret }}
  labels:
{{ include "huginn.labels" . | indent 4 }}    
type: Opaque
data:
  smtp_domain: {{ .Values.smtp.domain | b64enc }}
  smtp_username: {{ .Values.smtp.username | b64enc }}
  smtp_password: {{ .Values.smtp.password | b64enc }}
  smtp_server: {{ .Values.smtp.server | b64enc }}
  smtp_port: {{ toString .Values.smtp.port | b64enc }}
  smtp_authmode: {{ .Values.smtp.authentication | b64enc }}
  smtp_starttls: {{ toString .Values.smtp.starttls | b64enc }}

  invitiation_code: {{ .Values.invitation_code | b64enc }}

  db_addr: {{ default ( printf "%s.%s.svc.cluster.local" .Values.postgresql.fullnameOverride .Release.Namespace ) .Values.db.address | b64enc }}
  db_port: {{ toString .Values.db.port | b64enc }}
  db_user: {{ .Values.db.username | b64enc }}
  db_pass: {{ .Values.db.password | b64enc }}
  db_adapter: {{ "postgresql" | b64enc }}

  twitter_key: {{ .Values.twitter.oauth.key | b64enc }}
  twitter_secret: {{ .Values.twitter.oauth.secret | b64enc }}
