version: "3.2"

services:
  jackett:
    image: linuxserver/jackett:latest
    env_file: /var/data/config/jackett/jackett.env
    volumes:
      - /var/data/media/:/media
      - /var/data/jackett:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:jackett.example.com
        - traefik.port=9117    
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.jackett.rule=Host(`jackett.example.com`)"
        - "traefik.http.routers.jackett.entrypoints=https"
        - "traefik.http.services.jackett.loadbalancer.server.port=9117"
        - "traefik.http.routers.jackett.middlewares=forward-auth"
    networks:
      - traefik_public
      - autopiratev2_public

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true