kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: miniflux-db
  namespace: miniflux
  annotations:
    backup.kubernetes.io/deltas: P1D P7D
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
