kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.claims.media.name }}
  labels:
  {{- include "autopirate.labels" . | indent 4 }}  
  {{- range $key, $value := .Values.claims.media.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
    {{- range $key, $value := .Values.claims.media.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.claims.media.accessMode }}
  storageClassName: {{ .Values.claims.media.storageClass }}
  resources:
    requests:
      storage: {{ .Values.claims.media.size }}