version: '3.4'

services:
  redmine:
    image: redmine
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    tty: true
    ports:
      - ${PORT}:3000
    environment:
    




  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine