version: "3"

services:
  shepherd-app:
    image: mazzolino/shepherd
    container_name: shepherd
    env_file : /docker/shepherd/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=false"
    deploy:
      placement:
        constraints: [node.role == manager]