version: '3.4'

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs-server
    environment:
      - SHARED_DIRECTORY=/nfsshare
    volumes: 
    - /netdata:/nfsshare
    tty: true
    network_mode: "bridge"
    ports: 
        - 2049:2049
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    privileged: true
    restart: unless-stopped