version: '3'

services:
  ghost:
    image: ghost:1-alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/data/ghost/:/var/lib/ghost/content
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:ghost.funkypenguin.co.nz
        - traefik.docker.network=traefik
        - traefik.port=2368

networks:
  traefik_public:
    external: true
