version: '3.4'

services:
  ftp-server:
    image: fauria/vsftpd
    container_name: ftp_server
    environment:
      - FTP_USER=server
      - FTP_PASS=homel@nd
    volumes: 
    - vsftpd_log:/var/log/vsftpd
    - ${MOUNT}:/home/vsftpd
    tty: true
    network_mode: "bridge"
    ports: 
        - 20:20
        - 21:21
    restart: unless-stopped
volumes:
  vsftpd_log: