version: "3.0"

services:
  plex:
    image: linuxserver/plex
    env_file: /var/data/config/plex/plex.env
    volumes:
      - /var/data/plex/config:/config
      - /srv/data/:/data
    deploy:
      labels:
        - traefik.frontend.rule=Host:plex.funkypenguin.co.nz
        - traefik.docker.network=traefik_public
        - traefik.port=32400
    networks:
      - traefik_public
      - internal
    ports:
      - 32469:32469
      - 32400:32400
      - 32401:32401
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  tautulli:
    image: linuxserver/tautulli:latest
    env_file: /var/data/config/plex/tautulli.env
    volumes:
      - /srv/data/:/data
      - /var/data/autopirate/tautulli:/config
    networks:
      - internal

  tautulli_proxy:
    image: a5huynh/oauth2_proxy
    env_file: /var/data/config/plex/tautulli.env
    dns_search: hq.funkypenguin.co.nz
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:tautulli.funkypenguin.co.nz
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /var/data/config/plex/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://tautulli:8181
      -redirect-url=https://tautulli.funkypenguin.co.nz
      -http-address=http://0.0.0.0:4180
      -email-domain=example.com
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt

  nowshowing:
    image: ninthwalker/nowshowing:v2
    env_file: /var/data/config/plex/nowshowing.env
    volumes:
      - /var/pdata/nowshowing/config:/config:rw
    networks:
      - internal

  nowshowing_proxy:
    image: funkypenguin/oauth2_proxy
    env_file: /var/data/config/plex/nowshowing.env
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:nowshowing.funkypenguin.co.nz
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /var/data/config/plex/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://nowshowing:6878
      -redirect-url=https://nowshowing.funkypenguin.co.nz
      -http-address=http://0.0.0.0:4180
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt

  plex-cron:
    image: funkypenguin/htpc-cron
    volumes:
      - /srv/data/:/data
      - /usr/share/zoneinfo/Pacific/Auckland:/etc/localtime:ro
      - /var/data/plex/plex-cron:/config:ro
    networks:
      - internal

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.16.0/24
