version: '3.4'

volumes: 
  radarr_config:

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
    volumes: 
      - radarr_config:/config
      - ${MOVIESDIR}:/movies
      - ${WATCHDIR}:/downloads
    tty: true
    network_mode: "bridge"
    ports: 
      - ${PORT}:7878
    restart: unless-stopped
