version: "3.7"

########################### NETWORKS
networks:
  local1:
    driver: bridge
  # t2_proxy:
  #   driver: bridge
  # homelab:
  #   name: homelab_lan1
  #   driver: macvlan
  #   driver_opts: 
  #     parent: enp1s0
  #   ipam:
  #     driver: default
  #     config: 
  #       - subnet: 192.168.1.0/24

########################### VOLUMES
# volumes:


########################### SERVICES
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/radarr/config:/config
      - ${MOVIESDIR}:/movies
      - ${DOWNLOADDIR}:/downloads
    ports:
      - ${RADARRPORT}:7878
    restart: unless-stopped

  sonarr:
      image: ghcr.io/linuxserver/sonarr
      container_name: sonarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - ${CONFIGDIR}/sonarr/config:/config
        - ${TVDIR}:/tv
        - ${DOWNLOADDIR}:/downloads
      ports:
        - ${SONARRPORT}:8989
      restart: unless-stopped