version: "3.7"

########################### NETWORKS
networks:
  services:
    driver: bridge
  # t2_proxy:
  #   driver: bridge
  # homelab:
  #   name: homelab_lan1
  #   driver: macvlan
  #   driver_opts: 
  #     parent: enp1s0
  #   ipam:
  #     driver: default
  #     config: 
  #       - subnet: 192.168.1.0/24

########################### VOLUMES
# volumes:


########################### SERVICES
services: