version: "3.7"

########################### NETWORKS
networks:
  local1:
    driver: bridge
  # t2_proxy:
  #   driver: bridge
  # homelab:
  #   name: homelab_lan1
  #   driver: macvlan
  #   driver_opts: 
  #     parent: enp1s0
  #   ipam:
  #     driver: default
  #     config: 
  #       - subnet: 192.168.1.0/24

########################### VOLUMES
# volumes:


########################### SERVICES
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/radarr/config:/config
      - ${MOVIESDIR}:/movies
      - ${DOWNLOADDIR}:/downloads
    ports:
      - ${RADARRPORT}:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/sonarr/config:/config
      - ${TVDIR}:/tv
      - ${DOWNLOADDIR}:/downloads
    ports:
      - ${SONARRPORT}:8989
    restart: unless-stopped

  mylar3:
    image: ghcr.io/linuxserver/mylar3
    container_name: mylar3
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIGDIR}/mylar:/config
      - ${COMICDIR}:/comics
      - ${DOWNLOADDIR}:/downloads
    ports:
      - ${MYLARPORT}:8090
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/bazarr/config:/config
      - ${MOVIESDIR}:/movies #optional
      - ${TVDIR}:/tv #optional
    ports:
      - ${BAZARRPORT}:6767
    restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/lidarr/config:/config
      - ${MUSICDIR}:/music
      - ${DOWNLOADDIR}:/downloads
    ports:
      - ${LIDARRPORT}:8686
    restart: unless-stopped

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PIHOLEGUIPASSWORD}
      # - CLI_ARGS= #optional
    volumes:
      - ${CONFIGDIR}/calibre:/config
      - ${BOOKSDIR}:/books
    ports:
      - ${CALIBREPORT1}:8080
      - ${CALIBREPORT2}:8081
    restart: unless-stopped

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ${CONFIGDIR}/calibreweb:/config
      - ${BOOKSDIR}:/books
    ports:
      - ${CALIBREWEBPORT}:8083
    restart: unless-stopped