version: "3.2"

services:
  nzbhydra:
    image: linuxserver/nzbhydra2:latest
    env_file: /var/data/config/nzbhydra/nzbhydra.env
    volumes:
      - /var/data/nzbhydra:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:nzbhydra.example.com
        - traefik.port=5076
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.nzbhydra.rule=Host(`nzbhydra.example.com`)"
        - "traefik.http.routers.nzbhydra.entrypoints=https"
        - "traefik.http.services.nzbhydra.loadbalancer.server.port=5076"
        - "traefik.http.routers.nzbhydra.middlewares=forward-auth"
    networks:
      - traefik_public
      - autopiratev2_public

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true