version: "3.7"
########################### Networks
networks:
  local1:
    driver: bridge
  # marketplace:
  #   external: true
  # warehouse:
  #   external: true
  # local0:
  #   driver: bridge    
  #   ipam:
  #     config:
  #       - subnet: 192.168.0.0/24
  # rollcall:
  #   driver: macvlan
  #   driver_opts: 
  #     parent: wlan0
  #   ipam:
  #     config: 
  #       - subnet: 192.168.1.0/24
########################### SERVICES
services: 
  tvheadend:
    image: ghcr.io/linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - /data/tvh/config:/config
      - /data/tvh/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/dvb:/dev/dvb #optional
    restart: unless-stopped

  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  cloudflare-ddns-capparelli:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CFDDNS0}
      - ZONE=capparelli.ie

  cloudflare-ddns-papercut:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CFDDNS1}
      - ZONE=papercut.design
  
  watchtower:
    image: containrrr/watchtower 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock