version: "3.7"

########################### NETWORKS
networks:
  homeland:
    driver: bridge
  # t2_proxy:
  #   driver: bridge
  homelab:
    name: homelab_lan
    driver: macvlan
    driver_opts: 
      parent: enp1s0
    ipam:
      driver: default
      config: 
        - subnet: 192.168.1.0/24

########################### VOLUMES
volumes:
  jackett_config:
  radarr_config:
  sonarr_config:

########################### SERVICES
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    networks: 
      homelab:
        ipv4_address: $PIHOLEIPADDR      # homelab:
    # ports:
    #   - 53:53/tcp
    #   - 53:53/udp
    #   - 67:67/udp
    #   - 80:80/tcp
    #   - 443:443/tcp
    environment:
      TZ: $TZ
      WEBPASSWORD: $PIHOLEGUIPASSWORD
      DNS1: 127.0.0.1
      DNS2: 1.0.0.1
    volumes:
      - $CONFIGDIR/pihole/etc/:/etc/pihole
      - $CONFIGDIR/pihole/dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    tty: true
    dns:
      - 127.0.0.1

  delugevpn:
    image: binhex/arch-delugevpn
    container_name: delugevpn
    networks: 
      homeland:
    environment: 
      - TZ=$TZ
      - VPN_ENABLED=yes
      - VPN_USER=$VPNUSER
      - VPN_PASS=$VPNPASSWORD
      - VPN_PROV=$VPNPROVIDER
      - STRICT_PORT_FORWARD=no 
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=$SETNETWORK
      - NAME_SERVERS=$DNSSERVERS
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - ADDITIONAL_PORTS=1234
      - DEBUG=false
      - UMASK=$DELUGEUMASK
      - PUID=$DELUGEPUID
      - PGID=$DELUGEPGID
    volumes: 
       - $CONFIGDIR/deluge/config:/config
       - $CONFIGDIR/deluge/data:/data
       - $TEMPDIR:/tmp 
       - $DOWNLOADDIR:/downloads
       - $WATCHDIR:/watch 
    tty: true
    cap_add: 
      - NET_ADMIN
    ports: 
      - 58846:58846
      - 58946:58946
      - $DELUGEPORT:8112
      - $PRIVOXYPORT:8118
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    networks: 
      homeland:
    environment: 
      - TZ=$TZ
      - PGID=$PGID
      - PUID=$PUID
    volumes: 
      - jackett_config:/config
      - $WATCHDIR:/watch
    tty: true
    ports: 
      - $JACKETTPORT:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment: 
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
    volumes: 
      - radarr_config:/config
      - $MOVIESDIR:/movies
      - $MOVIEDROPDIR:/downloads
    tty: true
    networks:
      homeland:
    ports: 
      - $RADARRPORT:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment: 
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      # - UMASK_SET=000
    volumes:
      - sonarr_config:/config
      - ${TVDIR}:/tv
      - ${TVDROPDIR}:/downloads
    tty: true
    networks:
      homeland:
    ports:
      - ${SONARRPORT}:8989
    restart: unless-stopped

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - $HOMEASSISCONFIGDIR:/config
    environment:
      - TZ=$TZ
    restart: always
    networks:
      homelab:
        ipv4_address: $HOMEASSISTIPADDR
      
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CLOUDFLARE_TRFK_API}
      - ZONE=$DOMAINNAME
      # - SUBDOMAIN=monitor
      - PROXIED=true

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.papercut.design`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mydnschallenge"

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    networks: 
      homeland:
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - URL=$DOMAINNAME
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - CERTPROVIDER=zerossl
      - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=<token> #optional
      - EMAIL=$CLOUDFLARE_EMAIL
      - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS=<extradomains> #optional
      - STAGING=false #optional
    volumes:
      - $CONFIGDIR/swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped