version: "3.7"

########################### NETWORKS
networks:
  keepalived:
    driver: bridge

########################### VOLUMES
volumes:
  FOSS:

########################### SERVICES
services:
  service1:
    container_name: FOSS
    image: FOSS/FOSS:FOSS
    restart: unless-stopped
    # command: # CLI arguments
      # - --FOSS
    networks:
      default:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - FOSS:/directory_in_container
    environment:
      - FOSS=FOSS