version: '3.4'

services:
  watchtower:
    image: code
    container_name: watchtower_homeland
    environment: 
      - 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
    tty: true
    network_mode: "bridge"
    restart: unless-stopped
