version: "3.7"
########################### Networks
networks:
  local1:
  marketplace:
    external: true
  warehouse:
    external: true
  # local0:
  #   driver: bridge    
  #   ipam:
  #     config:
  #       - subnet: 192.168.0.0/24
  # rollcall:
  #   driver: macvlan
  #   driver_opts: 
  #     parent: wlan0
  #   ipam:
  #     config: 
  #       - subnet: 192.168.1.0/24
########################### SERVICES
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    networks: 
      rollcall:
        ipv4_address: ${HEIMDALLIPADDR}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/heimdall_config:/config
    networks: 
      - local1
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  cf-ddns:
    container_name: cf-ddns
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CF_DDNS_API_KEY}
      - ZONE=${DOMAINNAME}
      - PROXIED=true
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1