{{- if and .Values.ingress.enabled ( eq .Values.ingress.type "kube" ) -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.names.service }}
  labels:
{{ include "huginn.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ .Values.names.service }}
              servicePort: {{ .Values.app.service.internalPort }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}