{{ if .Values.certmanager.enabled | default false }}
# Per https://certmanager.io/docs/configuration/acme/
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.certmanager.letsencrypt.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: "letsencrypt-prod-issuer-account-key" # Insert values from values.yaml here
    solvers:
    - dns01:
{{ if .Values.certmanager.letsencrypt.dns01.cloudflare.enabled | default false }}
        cloudflare:
          email: {{ .Values.certmanager.letsencrypt.dns01.cloudflare.email | default "none" }}
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
{{ end }}
{{ end }}