---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "letsencrypt-secrets"
data:
#  An example of creating a secret based on a file stored with the chart
#  foo: {{ .Files.Get "files/etc/foo.xml" | b64enc | quote}}
#  An example of creating a secret based on a value in values.yaml
{{ if .Values.certmanager.letsencrypt.dns01.cloudflare.enabled | default false }}
  cloudflare-api-token-secret: {{ .Values.certmanager.letsencrypt.dns01.cloudflare.api_token | default "cloudflare-api-key-not-correctly-set" | b64enc | quote }}
{{ end }}
