version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8081:8069"
    volumes:
      - /netdata/odoo/addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
      - odoo-web-etc:/etc/odoo
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /netdata/odoo/odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-web-etc:
