version: '2'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8081:8069"
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo