version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8081:8069"
    volumes:
      - /local/odoo/addons:/mnt/extra-addons
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /local/odoo/odoo-db-data:/var/lib/postgresql/data/pgdata
