version: "3.2"

services:
  headphones:
    image: linuxserver/headphones:latest
    env_file: /var/data/config/headphones/headphones.env
    volumes:
      - /var/data/media/:/media
      - /var/data/headphones:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:headphones.example.com
        - traefik.port=8181
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.headphones.rule=Host(`headphones.example.com`)"
        - "traefik.http.routers.headphones.entrypoints=https"
        - "traefik.http.services.headphones.loadbalancer.server.port=8181"
        - "traefik.http.routers.headphones.middlewares=forward-auth"
    networks:
      - traefik_public
      - autopiratev2_public

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true