version: "3.2"

services:
  sonarr:
    image: linuxserver/sonarr:latest
    env_file: /var/data/config/sonarr/sonarr.env
    volumes:
      - /var/data/media/:/media
      - /var/data/sonarr:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:sonarr.example.com
        - traefik.port=8989
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.sonarr.rule=Host(`sonarr.example.com`)"
        - "traefik.http.routers.sonarr.entrypoints=https"
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
        - "traefik.http.routers.sonarr.middlewares=forward-auth"
        
    networks:
      - traefik_public
      - autopiratev2_public 

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true