---
version: "2"

services:
  zammad-nginx:
    environment:
      - VIRTUAL_HOST=helpdesk.domain.tld
      - NGINX_SERVER_SCHEME=https
    networks:
      - default
      - proxy_2_zammad

networks:
  proxy_2_zammad:
    external:
      name: proxy_2_apps
