version: '3.1'

services:
  app:
    image: minio/minio
    env_file: /var/data/config/minio/minio.env
    volumes:
     - /var/data/minio/data:/data
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:minio.funkypenguin.co.nz
        - traefik.port=9000
    command:  minio server /data

networks:
  traefik_public:
    external: true
