[http.routers]
  [http.routers.pihole-rtr]
      entryPoints = ["https"]
      rule = "HostHeader(`pihole.papercut.design`)"
      service = "pihole-svc"
      middlewares = ["chain-authelia", "pihole-add-admin"]
      [http.routers.pihole-rtr.tls]
        certresolver = "dns-cloudflare"

[http.middlewares]
  [http.middlewares.pihole-add-admin.addPrefix]
    prefix = "/admin"

[http.services]
  [http.services.pihole-svc]
    [http.services.pihole-svc.loadBalancer]
      passHostHeader = true
      [[http.services.pihole-svc.loadBalancer.servers]]
        url = "http://192.168.1.100:80" # or whatever your external host's IP:port is