[http.middlewares]
  [http.middlewares.chain-no-auth]
    [http.middlewares.chain-no-auth.chain]
      middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers"]

  [http.middlewares.chain-basic-auth]
    [http.middlewares.chain-basic-auth.chain]
      middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers", "middlewares-basic-auth"]

  # [http.middlewares.chain-oauth]
  #   [http.middlewares.chain-oauth.chain]
  #     middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers", "middlewares-oauth"]

  # [http.middlewares.chain-authelia]
  #   [http.middlewares.chain-authelia.chain]
  #     middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers", "middlewares-authelia"]