version: "3.0"

services:
  jellyfin:
    image: jellyfin/jellyfin
    env_file: /var/data/config/jellyfin/jellyfin.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/data/jellyfin/:/config
      - /srv/data/:/data
    labels:
      - traefik.frontend.rule=Host:jellyfin.funkypenguin.co.nz
      - traefik.docker.network=traefik_public
      - traefik.port=8096
    networks:
      - traefik_public

networks:
  traefik_public
    external: true  
