version: '3.4'

networks: 
  lan:
    name: org_lan
    driver: macvlan
    driver_opts: 
      parent: enp1s0
    ipam:
      config: 
        - subnet: 192.168.1.0/24

services:
  organizr:
    image: linuxserver/organizr
    container_name: a_organizr
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes: 
      - ./config:/config
    tty: true
    networks: 
      lan:
        ipv4_address: 192.168.1.100
    # ports: 
    restart: unless-stopped
