version: '3.4'

networks: 
  outside:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

services:
  organizr:
    image: linuxserver/organizr
    container_name: a_organizr
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes: 
      - ./config:/config
    tty: true
    networks: 
      default:
      outside:
        ipv4_address: 192.168.1.100
    # ports: 
    restart: unless-stopped
