language: python
dist: bionic
python:
  - '3.8'
services:
  - redis
before_install:
  # We use Debian Buster for our Docker image but the closest distro we can get in Travis is Ubuntu Bionic. This upgrades the version of GLIBC so that our custom Tensorflow build works.
  - sudo sed -i 's/bionic/focal/g' /etc/apt/sources.list
  - sudo apt update
  - sudo apt install -y libc-bin libimage-exiftool-perl dcraw wget
install:
  - pip install -r requirements.txt
script:
  - coverage run test.py
after_success:
  - pip install codecov
  - codecov
