version: '3.4'

services:
  xteve:
    image: bl0m1/xtevedocker:latest
    container_name: c_xteve
    # environment: 
    volumes: 
      - ./config:/home/xteve
    tty: true
    network_mode: "bridge"
    ports: 
      - ${PORT}:34400
    restart: unless-stopped
