{{ $app := .Values.apps.nzbget }} {{ $fullname := printf "%s-%s-%s" .Release.Name $app.name .Chart.Name | trunc 63 | trimSuffix "-" }}
{{- if $app.enable  -}}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $fullname }}
  labels:
  {{- include "autopirate.labels" . | indent 4 }}  
  {{- range $key, $value := $app.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 $app.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ $app.name }}
        image: "{{ $app.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ $app.port | int }}

        livenessProbe:
        # We get a 401 when we try query over http
        #  httpGet:
        #    path: /
        #    port: {{ $app.port | int }}
        # However - 127.0.0.1 is a trusted IP address :)
          exec:
            command:
              - curl
              - http://127.0.0.1:{{ $app.port }}
          initialDelaySeconds: 30
        startupProbe:
          exec:
            command:
              - curl
              - http://127.0.0.1:{{ $app.port }}
          failureThreshold: 30
          periodSeconds: 10
        
        readinessProbe:
          exec:
            command:
              - curl
              - http://127.0.0.1:{{ $app.port }}
        resources:
{{ toYaml $app.resources | indent 10 }}
        volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: media
              mountPath: /media

              # We include a bootstrap config for 99% of people who are using this chart in combination with an auth proxy
            - name: bootstrap 
              mountPath: /etc/cont-init.d/98-config-bootstrap-kube
              subPath: 'bootstrap'
      volumes:
          - name: media
            persistentVolumeClaim:
              claimName: {{ .Values.claims.media.name }}
          - name: downloads
            persistentVolumeClaim:
              claimName: {{ .Values.claims.download.name }}
          - name: config
            persistentVolumeClaim:
              claimName: {{ $fullname }}
          - name: bootstrap
            configMap:
              name: {{ $fullname }}
              defaultMode: 511 #777 but in decimal not octal
{{- end -}}