version: "3.7"
########################### Networks
networks:
  local1:
  marketplace:
    external: true
  warehouse:
    external: true
  # local0:
  #   driver: bridge    
  #   ipam:
  #     config:
  #       - subnet: 192.168.0.0/24
  # rollcall:
  #   driver: macvlan
  #   driver_opts: 
  #     parent: wlan0
  #   ipam:
  #     config: 
  #       - subnet: 192.168.1.0/24
########################### SERVICES
services: 

  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /home/server/data/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped

  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

  mariadb:
      image: mariadb:latest
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dolibarr

  dolibar:
      image: tuxgasy/dolibarr
      environment:
          DOLI_DB_HOST: mariadb
          DOLI_DB_USER: root
          DOLI_DB_PASSWORD: root
          DOLI_DB_NAME: dolibarr
          DOLI_URL_ROOT: 'http://192.168.1.6'
          PHP_INI_DATE_TIMEZONE: 'Europe/Dublin'
      ports:
          - "8070:80"
      links:
          - mariadb