version: "3.7"
########################### Networks
networks:
  local1:
  marketplace:
    external: true
  warehouse:
    external: true
  # local0:
  #   driver: bridge    
  #   ipam:
  #     config:
  #       - subnet: 192.168.0.0/24
  # rollcall:
  #   driver: macvlan
  #   driver_opts: 
  #     parent: wlan0
  #   ipam:
  #     config: 
  #       - subnet: 192.168.1.0/24
########################### SERVICES
services: 

  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  watchtower:
    image: containrrr/watchtower 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      # - CLI_ARGS= #optional
    volumes:
      - ${DATADIR}/duplicati/config:/config
      - ${DATADIR}/duplicati/backups:/backups
      - ${DATADIR}/duplicati/source:/source
      - /local:/localdata
    ports:
      - 8200:8200
    restart: unless-stopped