version: "3.7"
########################### Networks
networks:
  local1:
    external: true
  default:

########################### SERVICES
services: 
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: ${TZ}
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn:/vpn

  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DATADIR}/deluge/config:/config
      - ${DATADIR}/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped



  # Replace "service1" with and image with an actual service you want to run
  service1:
    image: docker_hub_user/container_name
    depends_on:
      - vpn
    environment:
      TZ: ${TZ}
    network_mode: "service:vpn"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /srv/service1:/var/lib/service1:Z

