version: "2.1"
########################### Networks
networks:
  local1:

########################### SERVICES
services: 

  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  watchtower:
    image: containrrr/watchtower 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      # - CLI_ARGS= #optional
    volumes:
      - 'C:\dockerdata\duplicati\config:/config'
      - 'C:\dockerdata\duplicati\backups:/backups'
      - 'C:\dockerdata\duplicati\source:/source'
      - 'C:\dockerdata:/localdata'
    ports:
      - 8200:8200
    restart: unless-stopped

  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8383:8080
      - 8883:8443
    environment:
      PUBLIC_DNS: mind.capparelli.ie
      ORGANISATION_UNIT: unit
      ORGANISATION: papercut
      CITY: Belfast
      STATE: NIreland
      COUNTRY_CODE: UK
    volumes:
      - C:\dockerdata\drawio:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://mind.capparelli.ie || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
