version: "3.2"

services:
  mylar:
    image: linuxserver/mylar3:latest
    env_file: /var/data/config/mylar/mylar.env
    volumes:
      - /var/data/media/:/media
      - /var/data/mylar:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:mylar.example.com
        - traefik.port=8090
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.mylar.rule=Host(`mylar.example.com`)"
        - "traefik.http.routers.mylar.entrypoints=https"
        - "traefik.http.services.mylar.loadbalancer.server.port=8090"
        - "traefik.http.routers.mylar.middlewares=forward-auth"
    networks:
      - traefik_public
      - autopiratev2_public

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true