version: "3"

services:
  app:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/data/portainer:/data
    networks:
      - internal
    deploy:
      placement:
        constraints: [node.role == manager]                                                   
    command: -H unix:///var/run/docker.sock 

  proxy:
    image: a5huynh/oauth2_proxy
    env_file : /var/data/config/portainer/portainer.env
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:portainer.funkypenguin.co.nz
        - traefik.port=4180
        - traefik.docker.network=traefik_public
    volumes:
      - /var/data/config/portainer/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://app:9000
      -redirect-url=https://portainer.funkypenguin.co.nz
      -http-address=http://0.0.0.0:4180
      -email-domain=funkypenguin.co.nz
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt
     
networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.12.0/24 
