# Name everything!
names:

  # The name of the deployment
  deployment: <CHARTNAME>

  # The name of the service
  service: <CHARTNAME>

  # The name of the secret
  secret: <CHARTNAME>

  # The name of the Ingress rule
  ingress: <CHARTNAME>

app:
  # The number of pods this app should start and maintain
  replicas: 1

  # Labels are customizable to how you like.
  labels:

    # App is the only required label
    app: <CHARTNAME>

  # Set the resources you want to allocate to each pod
  resources: {}

  image:

    # The image to use for this deployment, changing it is not recommended.
    image: <CHARTNAME>/<CHARTNAME>

    # The Image Pull Policy (The same one if you were writing it yourself!)
    pullPolicy: IfNotPresent

  service:

    # The port the service exposes on the deployment
    internalPort: NOTAREALPORT

    # The name of the port
    name: http-<CHARTNAME>

  probes:
    liveness:

      # An HTTP path on the container that will return something if it is all live and healthy
      httpPath: /

    readiness:

      # An HTTP path on the container that will return something when the container is classified as "Ready"
      httpPath: /

ingress:

  # Enabled Ingress for this deployment
  enabled: true

  # Either `traefik` or `kube`, Defines the type of ingress rule to use
  type: kube

  # The host you can access this service at
  host: <CHARTNAME>.local

  # A path you can access it at, It is not recommended to change it off `/`
  path: /

  # TLS Settings for Ingress
  tls: {}

  # Annotations for the ingress
  annotations: {}