version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: homeland
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_proc:/host/proc:ro
      - netdata_sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  netdata_proc:
  netdata_sys: