version: '3'
networks:
  traefik:
    external: true
  internal:

services:

  db:
    restart: always
    image: postgres:alpine
    networks:
      - internal
    volumes:
      - /var/data/runtime/mastodon/database:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
    networks:
      - internal
    volumes:
      - /var/data/runtime/mastodon/redis:/data

  web:
    image: gargron/mastodon
    restart: always
    env_file: /var/data/config/mastodon/mastodon.yml
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    deploy:
      labels:
        - traefik.frontend.rule=Host:mastodon.funkypenguin.co.nz
        - traefik.docker.network=traefik
        - traefik.port=3000
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    networks:
      - internal
      - traefik
    volumes:
      - /var/data/mastodon/public/assets:/mastodon/public/assets
      - /var/data/mastodon/public/packs:/mastodon/public/packs
      - /var/data/mastodon/public/system:/mastodon/public/system

  streaming:
    image: gargron/mastodon
    env_file: /var/data/mastodon/.env.production
    command: npm run start
    networks:
      - internal
      - traefik
    deploy:
      labels:
        - traefik.frontend.rule=Path:/api
        - traefik.docker.network=traefik
        - traefik.port=4000

  sidekiq:
    image: gargron/mastodon
    restart: always
    networks:
      - internal
    env_file: /var/data/mastodon/.env.production
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    volumes:
      - /var/data/mastodon/public/system:/mastodon/public/system
