version: '3.4'

services:
  handbrake:
    image: jlesage/handbrake
    container_name: a_handbrake
    # environment: 
    volumes: 
      - ${CONFIG}:/config
      - ${STORAGE}:/storage
      - ${WATCHDIR}:/watch
      - ${OUTPUTDIR}:/output
    tty: true
    network_mode: "bridge"
    ports:
      - ${PORT}:5800 
    restart: unless-stopped
