########################### Networks
# networks:
#   local1:
#     name: local1
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.10.0/24"

########################### Volumes
# volumes:

services:
  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    # networks:
    #   local1:
    #     ipv4_address: 192.168.10.90
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped 
    networks:
      - default
    command: -H unix:///var/run/docker.sock 
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - ${DATA_DIR}/portainer/data:/data 
    environment:
      - TZ=$TZ
  
  rtmp_server:
    container_name: rtmp_server
    image: tiangolo/nginx-rtmp
    restart: always
    ports:
      - "1935:1935"
