version: "3.7"
########################### Networks
# networks:
#   local1:
#     name: local1
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.10.0/24"

########################### Volumes
# volumes:

services:
  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    # networks:
    #   local1:
    #     ipv4_address: 192.168.10.90
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  socketproxy:
    container_name: socketproxy
    image: tecnativa/docker-socket-proxy
    restart: always
    privileged: true
    ports:
      - '2376:2375'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - APP_URL=http://192.168.1.208:9292
      - MYSQL_PORT_3306_TCP_ADDR=192.168.1.208
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=${SNIPE_DB}
      - MYSQL_USER=${SNIPE_DB_USER}
      - MYSQL_PASSWORD=${SNIPE_DB_PASSWORD}
    volumes:
      - /home/server/data/snipeit:/config
    ports:
      - 9292:80

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${SNIPE_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${SNIPE_DB}
      - MYSQL_USER=${SNIPE_DB_USER}
      - MYSQL_PASSWORD=${SNIPE_DB_PASSWORD}
    volumes:
      - /home/server/data/snipe_db:/config
    ports:
      - 3306:3306
    restart: unless-stopped