version: "3.7"
########################### Networks
# networks:
#   local1:
#     name: local1
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.10.0/24"

########################### Volumes
volumes:
  cache:

services:
  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    # networks:
    #   local1:
    #     ipv4_address: 192.168.10.90
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  socketproxy:
    container_name: socketproxy
    image: tecnativa/docker-socket-proxy
    restart: always
    # networks:
    #   local1:
    #     ipv4_address: 192.168.10.91
    privileged: true
    ports:
      - '2376:2375'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  netbox:
    image: lscr.io/linuxserver/netbox:latest
    container_name: netbox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUPERUSER_EMAIL=${NB_SUSER_EMAIL}
      - SUPERUSER_PASSWORD=${NB_SUSER_PASSWD}
      - ALLOWED_HOST=${NB_ALLOWED_HOST}
      - DB_NAME=${NB_DB_NAME}
      - DB_USER=${NB_DB_USER}
      - DB_PASSWORD=${NB_DB_PASSWD}
      - DB_HOST=192.168.1.208
      - DB_PORT=5432
      - REDIS_HOST=192.168.1.208
      - REDIS_PORT=6379
      # - REDIS_PASSWORD=${NB_REDIS_PASSWD}
      - REDIS_DB_TASK=0
      - REDIS_DB_CACHE=1
      # - BASE_PATH= #optional
    volumes:
      - /home/server/data/netbox:/config
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - netbox-postgres
      - netbox-cache

  netbox-postgres:
    container_name: netbox-postgres
    restart: unless-stopped
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - /home/server/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${NB_DB_PASSWD}
      - POSTGRES_USER=${NB_DB_USER}
      - POSTGRES_DB=${NB_DB_NAME}

  netbox-cache:
    image: redis:7-alpine
    container_name: netbox-cache
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel verbose
    volumes: 
      - cache:/data
