version: '3.4'

services:
  delugevpn:
    image: binhex/arch-delugevpn
    container_name: delugevpn
    environment: 
      - TZ=${TZ}
      - VPN_ENABLED=yes
      - VPN_USER=${VPNUSER}
      - VPN_PASS=${VPNPASSWORD}
      - VPN_PROV=${VPNPROVIDER}
      - STRICT_PORT_FORWARD=no 
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=${SETNETWORK}
      - NAME_SERVERS=${DNSSERVERS}
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - ADDITIONAL_PORTS=1234
      - DEBUG=false
      - UMASK=${UMASK}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes: 
       - ${CONFIGDIR}:/config
       - ${DATADIR}:/data
       - ${TEMPDIR}:/tmp 
       - ${DOWNLOADDIR}:/downloads
       - ${WATCHDIR}:/watch 
    tty: true
    network_mode: "bridge"
    cap_add: 
      - NET_ADMIN
    ports: 
      - 58846:58846
      - 58946:58946
      - ${DELUGEPORT}:8112
      - ${PRIVOXYPORT}:8118
    restart: unless-stopped
