version: '3'

services:

  app:
    image: funkypenguin/archivy
    env_file: /var/data/config/archivy/archivy.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/data/archivy:/archivy
    networks:
      - internal   
      - traefik_public
    deploy:
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:archivy.example.com
        - traefik.port=5000
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.archivy.rule=Host(`archivy.example.com`)"
        - "traefik.http.routers.archivy.entrypoints=https"
        - "traefik.http.services.archivy.loadbalancer.server.port=5000"
        - "traefik.http.routers.archivy.middlewares=forward-auth"

  elasticsearch:
    image: elasticsearch:7.9.0
    volumes:
      - /var/data/runtime/archivy/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - internal      
    environment:
      - "discovery.type=single-node"

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.21.0/24
