---
networks:
  authnet:
    driver: bridge

name: authelia

services:
  auth:
    container_name: auth    
    image: authelia/authelia:latest
    ports:
      - 9091:9091
    volumes:
      - ./data/authelia/config:/config
    networks:
      - authnet
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb

  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/authelia/redis:/bitnami/
    environment:
    #   REDIS_PASSWORD: ${AUTH_REDIS_PASS}
        ALLOW_EMPTY_PASSWORD: true
    networks:
      - authnet
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./data/authelia/mariadb:/config
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_ROOT_PASS}
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: authelia
      MYSQL_USER: authelia
      MYSQL_PASSWORD: ${AUTH_USER_PASS}
    networks:
      - authnet
    restart: unless-stopped