services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/adguardhome/workdir:/opt/adguardhome/work
      - ${DATA_DIR}/adguardhome/confdir:/opt/adguardhome/conf
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.254

  cloudflare-ddns-capparelli:
    container_name: ddns_capparelli
    image: oznu/cloudflare-ddns:latest
    restart: always
    networks:
      k0_proxy:
        ipv4_address: 192.168.90.101
    environment:
      - API_KEY=${CFDDNS0}
      - ZONE=${CFDDN_ZONE_0}
