########################### Networks
networks:
  local1:
    name: local1
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"

########################### Volumes
volumes:
  authdb:
  authredis:

name: services

services:
  agent:
    ports:
        - ${PORTAINER_AGENT_PORT}:9001
    container_name: portainer_agent
    networks:
      local1:
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - default
    command: -H unix:///var/run/docker.sock 
    ports:
      - ${PORTAINER_PORT}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - ${DATA_DIR}/portainer/data:/data 
    environment:
      - TZ=$TZ

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAIN_NAME}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - PROPAGATION=30
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - EMAIL=${DNS_EMAIL}
      - ONLY_SUBDOMAINS=false
      - STAGING=false
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard
      - LC_ALL=${LOCALE}
    volumes:
      - ${DATA_DIR}/swag:/config
      - ${DATA_DIR}/html:/dump
      - ${DATA_DIR}/posts:/posts
    ports:
      - ${SWAG_SSL_PORT}:443
      - ${SWAG_PORT}:80 #optional
      - ${SWAG_GUI}:81
    restart: unless-stopped
    networks:
      local1:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - ${HOMEPAGE_PORT}:3000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DATA_DIR}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    restart: unless-stopped
    networks:
      local1:

  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/adguardhome/workdir:/opt/adguardhome/work
      - ${DATA_DIR}/adguardhome/confdir:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    image: adguard/adguardhome
    networks:
      local1: