version: "3.7"
########################### Networks
networks:
  local1:
    name: local1
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"

########################### Volumes
services:
  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    networks:
      local1:
        ipv4_address: 192.168.10.80
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  socketproxy:
    container_name: socketproxy
    image: tecnativa/docker-socket-proxy
    restart: always
    privileged: true
    ports:
      - '2376:2375'
    networks:
      local1:
        ipv4_address: 192.168.10.81
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAIN_NAME}
      - SUBDOMAINS=wildcard
      - PROPAGATION=30
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
      - EMAIL=${DNS_EMAIL}
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:universal-docker|linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-maxmind
    volumes:
      - ${DATA_DIR}/swag:/config
    ports:
      - 4443:443
      - 4480:80 #optional
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.82

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CODE_PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ${DATA_DIR}/code-server:/config
      - /:/host
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.83

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 10004:3000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DATA_DIR}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.84