########################### Networks
networks:
  local1:
    name: local1
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"

########################### Volumes
volumes:
  authdb:
  authredis:

services:
  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    networks:
      local1:
        ipv4_address: 192.168.10.80
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - default
    command: -H unix:///var/run/docker.sock 
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - ${DATA_DIR}/portainer/data:/data 
    environment:
      - TZ=$TZ

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAIN_NAME}
      - SUBDOMAINS=wildcard
      - PROPAGATION=30
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
      - EMAIL=${DNS_EMAIL}
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard
      - LC_ALL=${LOCALE}
    volumes:
      - ${DATA_DIR}/swag:/config
      - ${DATA_DIR}/html:/dump
      - /home/server/posts:/posts
    ports:
      - 4443:443
      - 4480:80 #optional
      - 4481:81
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.82

  auth:
    container_name: auth    
    image: authelia/authelia:latest
    ports:
      - 9091:9091
    volumes:
      - ./authelia:/config
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.83
    depends_on:
      - auth-redis
      - auth-mariadb

  auth-redis:
    container_name: auth-redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    volumes:
      - authredis:/bitnami/
    environment:
      REDIS_PASSWORD: ${AUTH_REDIS_PASS}
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.84

  auth-mariadb:
    container_name: auth-mariadb
    image: linuxserver/mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - authdb:/config
    environment:
      MYSQL_ROOT_PASSWORD: ${MSQL_ROOT_PW}
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: authelia
      MYSQL_USER: authelia
      MYSQL_PASSWORD: ${MSQL_PW}  
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.85

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 10004:3000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DATA_DIR}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.86
