version: "3.7"
########################### Networks
networks:
  local1:
    name: local1
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"

########################### Volumes
volumes:
  snipecache:
  snipedb:
  snipeit:

services:
  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    networks:
      local1:
        ipv4_address: 192.168.10.80
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  socketproxy:
    container_name: socketproxy
    image: tecnativa/docker-socket-proxy
    restart: always
    privileged: true
    ports:
      - '2376:2375'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - URL=${DOMAINNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - PROPAGATION=120
      - EMAIL=${DNSEMAIL}
      - ONLY_SUBDOMAINS=false
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-auto-reload|linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy #delete if not wanted or necessary
    volumes:
      - ${DATADIR}/swag:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    ports:
      - 18443:443
      - 1880:80
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.82

  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    networks:
      local1:
        ipv4_address: 192.168.10.83
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - APP_URL=https://assets.capparelli.ie
      - MYSQL_PORT_3306_TCP_ADDR=192.168.1.11
      - MYSQL_PORT_3306_TCP_PORT=3309
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=${SI_DB_PASSWORD}
    volumes:
      - ${DATADIR}/snipeit/config:/config
      - /netdata/swag/etc:/certs
    ports:
      - 8081:80
    restart: unless-stopped