version: "3.7"
########################### Networks
networks:
  local1:
    name: local1
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"

########################### Volumes
volumes:

services:
  agent:
    ports:
        - '9001:9001'
    container_name: portainer_agent
    networks:
      local1:
        ipv4_address: 192.168.10.80
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: portainer/agent

  socketproxy:
    container_name: socketproxy
    image: tecnativa/docker-socket-proxy
    restart: always
    privileged: true
    ports:
      - '2376:2375'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - URL=${DOMAINNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - PROPAGATION=120
      - EMAIL=${DNSEMAIL}
      - ONLY_SUBDOMAINS=false
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-auto-reload|linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy #delete if not wanted or necessary
    volumes:
      - ${DATADIR}/swag:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    ports:
      - 18443:443
      - 1880:80
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.82

  leantime:
    container_name: leantime
    restart: unless-stopped
    networks:
      local1:
        ipv4_address: 192.168.10.83
    ports:
      - '8088:80'
    depends_on:
      - leandb
    environment:
      - LEAN_DB_HOST=192.168.10.84
      - LEAN_DB_USER=leadtime
      - LEAN_DB_PASSWORD='vs9792gks899sf234g2'
      - LEAN_DB_DATABASE=leantime
      - LEAN_EMAIL_RETURN=dom@capparelli.ie
    image: 'leantime/leantime:latest'

  leandb:
    image: mysql:5.7
    restart: always
    container_name: leandb
    networks:
      local1:
        ipv4_address: 192.168.10.85
    environment:
      MYSQL_DATABASE: 'leantime'
      MYSQL_USER: 'leantime'
      MYSQL_PASSWORD: 'vs9792gks899sf234g2'
      MYSQL_ROOT_PASSWORD: 'b89f274ohfh9245tg35g'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ${DATADIR}/my-db:/var/lib/mysql