name: media_stack

networks:
  local1:
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - SERVER_REGIONS=Netherlands
    networks:
      local1:
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${DELUGE_GUI_PORT}:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
      - ${FLARESOLVERR_PORT}:8191
      - ${PROWLARR_PORT}:9696
      - ${RADARR_PORT}:7878
      - ${SONARR_PORT}:8989
      - ${READARR_PORT}:8787

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DATA_DIR}/deluge:/config
      - ${DATA_DIR}/downloads:/downloads
    network_mode: "container:gluetun"
    # ports:
    #   - 8112:8112
    #   - 6881:6881
    #   - 6881:6881/udp
    #   - 58846:58846 #optional
    restart: unless-stopped
    depends_on:
      - gluetun

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "container:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    # ports:
    #   - "${PORT:-8191}:8191"
    restart: unless-stopped
    depends_on:
      - gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/prowlarr:/config
    # ports:
    #   - 9696:9696
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      - gluetun

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/radarr:/config
      - ${MEDIADIR}/movies:/movies #optional
      - ${DATA_DIR}/downloads:/downloads #optional
    # ports:
    #   - 7878:7878
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      - gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/sonarr/:/config
      - ${MEDIADIR}/tv:/tv #optional
      - ${DATA_DIR}/downloads:/downloads #optional
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      - gluetun

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/readarr:/config
      - ${MEDIADIR}/library:/books #optional
      - ${DATA_DIR}/downloads:/downloads #optional
    # ports:
    #   - 8787:8787
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
