services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    networks:
      k0_proxy:
        ipv4_address: 192.168.90.102
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - SERVER_REGIONS=Netherlands
    volumes:
      - ${DATA_DIR}/gluetun:/gluetun
    ports:
      - ${DELUGE_GUI_PORT}:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
      - ${FLARESOLVERR_PORT}:8191
      - ${PROWLARR_PORT}:9696
      - ${RADARR_PORT}:7878
      - ${SONARR_PORT}:8989
      - ${READARR_PORT}:8787
      - ${OVERSEERR_PORT}:5055
      - ${BAZARR_PORT}:6767
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error # optional
    volumes:
      - ${DATA_DIR}/deluge:/config
      - ${DATA_DIR}/downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: "container:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/prowlarr:/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/radarr:/config
      - ${MEDIADIR}/movies:/movies # optional
      - ${DATA_DIR}/downloads:/downloads # optional
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/sonarr:/config
      - ${MEDIADIR}/tv:/tv # optional
      - ${DATA_DIR}/downloads:/downloads # optional
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  # overseerr:
  #   container_name: overseerr
  #   image: lscr.io/linuxserver/overseerr:latest
  #   network_mode: "container:gluetun"
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${DATA_DIR}/overseerr/config:/config
  #   depends_on:
  #     gluetun:
  #       condition: service_healthy
  #   restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/bazarr/config:/config
      - ${MEDIADIR}/movies:/movies # optional
      - ${MEDIADIR}/tv:/tv # optional
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr
    network_mode: bridge
    tty: true
    stdin_open: true
    environment:
      - serverIP=0.0.0.0
      - webUIPort=8265
      - serverPort=8266
      - TZ=Europe/Dublin
      - internalNode=true
      - inContainer=true
      - PUID=1000
      - PGID=1000
      - nodeName=knight0
    volumes:
      - /usb_media_storage/library/movies:/home/Tdarr/Media/movies
      - /usb_media_storage/library/tv:/home/Tdarr/Media/tv
      - ./data/downloads/cache/:/temp
      - ./data/tdarr/data/:/app/server
      - ./data/tdarr/data/:/app/configs
      - ./data/tdarr/data/:/app/logs
    ports:
      - 8265:8265
      - 8266:8266
    devices:
      - /dev/dri:/dev/dri
    logging:
      options:
        max-size: 10m
        max-file: 5
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055 # optional
    volumes:
      - ${DATA_DIR}/jellyseerr:/app/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "container:gluetun"
