services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DATA_DIR}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - SERVER_REGIONS=Netherlands
    networks:
      k0_proxy:
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${DELUGE_GUI_PORT}:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
      - ${FLARESOLVERR_PORT}:8191
      - ${PROWLARR_PORT}:9696
      - ${RADARR_PORT}:7878
      - ${SONARR_PORT}:8989
      - ${READARR_PORT}:8787
      - ${OVERSEERR_PORT}:5055
      - ${BAZARR_PORT}:6767
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DATA_DIR}/deluge:/config
      - ${DATA_DIR}/downloads:/downloads
    network_mode: "container:gluetun"
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "container:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/prowlarr:/config
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/radarr:/config
      - ${MEDIADIR}/movies:/movies #optional
      - ${DATA_DIR}/downloads:/downloads #optional
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/sonarr/:/config
      - ${MEDIADIR}/tv:/tv #optional
      - ${DATA_DIR}/downloads:/downloads #optional
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/overseerr/config:/config
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/bazarr/config:/config
      - ${MEDIADIR}/movies:/movies #optional
      - ${MEDIADIR}/tv:/tv #optional
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy

  tdarr:
    tty: true
    stdin_open: true
    volumes:
      - /usb_media_storage/library/movies:/home/Tdarr/Media/movies
      - /usb_media_storage/library/tv:/home/Tdarr/Media/tv
      - ./data/downloads/cache/:/temp
      - ./data/tdarr/data/:/app/server
      - ./data/tdarr/data/:/app/configs
      - ./data/tdarr/data/:/app/logs
    environment:
      - serverIP=0.0.0.0
      - webUIPort=8265
      - serverPort=8266
      - TZ=Europe/Dublin
      - PUID=1000
      - PGID=1000
    network_mode: bridge
    ports:
      - 8265:8265
      - 8266:8266
    logging:
      options:
        max-size: 10m
        max-file: 5
    devices:
      - /dev/dri:/dev/dri
    image: haveagitgat/tdarr