services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${DATA_DIR}/plex/library:/config
      - ${MEDIADIR}/tv:/tv
      - ${MEDIADIR}/movies:/movies
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://jellyfin.capparelli.ie
    volumes:
      - ${DATA_DIR}/jellyfin/library:/config
      - ${MEDIADIR}/tv:/data/tvshows
      - ${MEDIADIR}/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      k0_proxy:
        ipv4_address: 192.168.90.104
