services:
  nginxpm:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "4480:80" # Public HTTP Port
      - "4443:443" # Public HTTPS Port
      - "4481:81" # Admin Web Port
    volumes:
      - ${DATA_DIR}/nginxpm:/data
      - ${DATA_DIR}/letsencrypt:/etc/letsencrypt
    networks:
      k0_proxy:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      k0_proxy:

  qdirstat:
    image: lscr.io/linuxserver/qdirstat:latest
    container_name: qdirstat
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/qdirstat/config:/config
      - /:/data
    ports:
      - 9999:3000
      - 9998:3001
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/syncthing/config:/config
      - ${SYNC_DATA_DIR}:/data1
    ports:
      - ${SYNC_PORT_GUI:-8384}:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
