services:
  # nginxpm:
  #   image: "jc21/nginx-proxy-manager:latest"
  #   restart: unless-stopped
  #   ports:
  #     - "4480:80" # Public HTTP Port
  #     - "4443:443" # Public HTTPS Port
  #     - "4481:81" # Admin Web Port
  #   volumes:
  #     - ${DATA_DIR}/nginxpm:/data
  #     - ${DATA_DIR}/letsencrypt:/etc/letsencrypt
  #   networks:
  #     k0_proxy:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      HOMEPAGE_ALLOWED_HOSTS: home.capparelli.ie
    networks:
      k0_proxy:
        ipv4_address: 192.168.90.111

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/syncthing/config:/config
      - ${SYNC_DATA_DIR}:/data1
    ports:
      - ${SYNC_PORT_GUI:-8384}:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAIN_NAME}
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      # - CERTPROVIDER=
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION=30
      - EMAIL=${DNS_EMAIL}
      # - DISABLE_F2B=
      - SWAG_AUTORELOAD=true
      # - SWAG_AUTORELOAD_WATCHLIST=
    volumes:
      - ${DATA_DIR}/swag/config:/config
    ports:
      - 4443:443
      - 4480:80 #optional
    restart: unless-stopped
    networks:
      k0_proxy:
        ipv4_address: 192.168.90.112

  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    container_name: authelia
    image: authelia/authelia
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      k0_proxy:
        ipv4_address: 192.168.90.113
    ports:
      - "9091:9091"
    volumes:
      - ${DATA_DIR}/authelia/config:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  redis:
    image: redis:alpine
    container_name: auth_redis
    volumes:
      - ${DATA_DIR}/authelia/redis:/data
    networks:
      k0_proxy:
        ipv4_address: 192.168.90.114
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}