services:
  nginxpm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '4480:80' # Public HTTP Port
      - '4443:443' # Public HTTPS Port
      - '4481:81' # Admin Web Port
    volumes:
      - ${DATA_DIR}/nginxpm:/data
      - ${DATA_DIR}/letsencrypt:/etc/letsencrypt
    networks:
      k0_proxy:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID
      PGID: $PGID
    networks:
      k0_proxy: