{{- if and .Values.ingress.enabled ( eq .Values.ingress.type "traefik" ) -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.names.ingress }}
  labels:
{{ include "<CHARTNAME>.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  routes:
  - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
    kind: Rule
    services:
    - name: {{ .Values.names.service }}
      port: {{ .Values.app.service.internalPort }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}