version: "3.2"

services:
  radarr:
    image: linuxserver/sabnzbd
    env_file: /var/data/config/sabnzbd/sabnzbd.env
    volumes:
      - /var/data/media/:/media
      - /var/data/sabnzbd/:/config
    deploy:
      replicas: 1
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:sabnzbd.example.com
        - traefik.port=8080
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true        

        # traefikv2
        - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.example.com`)"
        - "traefik.http.routers.sabnzbd.entrypoints=https"
        - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
        - "traefik.http.routers.sabnzbd.middlewares=forward-auth"
    networks:
      - traefik_public
      - autopiratev2_public 

networks:
  traefik_public:
    external: true
  autopiratev2_public:
    external: true