services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      - socket_proxy
    command: -H tcp://socket-proxy:2375
    ports:
      - '9000:9000'
    volumes:
      - ${DATA_DIR}/portainer/data:/data
    environment:
      - TZ=$TZ

  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      socket_proxy:
    privileged: true
    ports:
      - 2375:2375
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - LOG_LEVEL=info
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=1
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1

  docker-gc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ['apps', 'all']
    networks:
      - socket_proxy
    volumes:
      - ${DATA_DIR}/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude
    environment:
      - CRON=12 0 0 * * ?
      - FORCE_IMAGE_REMOVAL=1
      - FORCE_CONTAINER_REMOVAL=0
      - GRACE_PERIOD_SECONDS=604800
      - DRY_RUN=0
      - CLEAN_UP_VOLUMES=1
      - TZ=$TZ
      - DOCKER_HOST=tcp://socket-proxy:2375
