services:
  homeassistant:
    container_name: homeassistant
    image: 'ghcr.io/home-assistant/home-assistant:stable'
    volumes:
      - ${DATA_DIR}/hassio:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    # devices:
    # - /dev/ttyUSB0:/dev/ttyUSB0

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ}
    ports:
      - '1880:1880'
    networks:
      - k0_proxy
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:
