services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: web_homepage
    restart: unless-stopped
    ports:
      - ${HOMEPAGE_PORT:-3000}:3000
    volumes:
      - ${DATA_DIR}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEPAGE_ALLOWED_HOSTS=home.${DOMAIN_NAME}

  cloudflare-ddns-capparelli:
    container_name: ddns_capparelli
    image: oznu/cloudflare-ddns:latest
    restart: always
    networks:
      k0_proxy:
    environment:
      - API_KEY=${CFDDNS0}
      - ZONE=${CFDDN_ZONE_0}
