version: "3.0"

services:
  shaarli:
    image: 'shaarli/shaarli:latest'
    env_file: /var/data/config/shaarli/shaarli.env    
    networks:
      - internal
    volumes:
      - /var/data/shaarli/cache:/var/www/shaarli/cache
      - /var/data/shaarli/data:/var/www/shaarli/data
  
  shaarli_proxy:
    image: funkypenguin/oauth2_proxy:latest
    env_file : /var/data/config/shaarli/shaarli.env
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:shaarli.funkypenguin.co.nz
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /share/Apps/config/shaarli/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://shaarli:8096
      -redirect-url=https://shaarli.funkypenguin.co.nz
      -http-address=http://0.0.0.0:4180
      -email-domain=gmail.com
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.38.0/24
