version: "3"

services:
  docker-cleanup:
    image: meltwater/docker-cleanup:latest
    container_name: cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    networks:
      - marketplace0
    deploy:
      mode: global
    env_file: /docker/docker_cleanup/docker-cleanup

networks:
  marketplace0:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.0.0/24
